// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                      metric.Meter
	mu                                         sync.Mutex
	registrations                              []metric.Registration
	ExporterAwss3LastSuccessfulUploadTimestamp metric.Int64Gauge
	ExporterAwss3UploadAttemptTotal            metric.Int64Counter
	ExporterAwss3UploadBytes                   metric.Int64Counter
	ExporterAwss3UploadFailedTotal             metric.Int64Counter
	ExporterAwss3UploadObjectSize              metric.Int64Histogram
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ExporterAwss3LastSuccessfulUploadTimestamp, err = builder.meter.Int64Gauge(
		"otelcol_exporter_awss3_last_successful_upload_timestamp",
		metric.WithDescription("Unix timestamp in seconds of the last successful S3 upload [Alpha]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterAwss3UploadAttemptTotal, err = builder.meter.Int64Counter(
		"otelcol_exporter_awss3_upload_attempt_total",
		metric.WithDescription("Number of started S3 upload attempts that reached the uploader [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterAwss3UploadBytes, err = builder.meter.Int64Counter(
		"otelcol_exporter_awss3_upload_bytes",
		metric.WithDescription("Final bytes uploaded to S3 after any exporter-level compression [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterAwss3UploadFailedTotal, err = builder.meter.Int64Counter(
		"otelcol_exporter_awss3_upload_failed_total",
		metric.WithDescription("Number of started S3 upload attempts that failed [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterAwss3UploadObjectSize, err = builder.meter.Int64Histogram(
		"otelcol_exporter_awss3_upload_object_size",
		metric.WithDescription("Final size in bytes of each successfully uploaded S3 object [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
