// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awss3receiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awss3receiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                           metric.Meter
	mu                              sync.Mutex
	registrations                   []metric.Registration
	ReceiverAwss3ObjectsDropped     metric.Int64Counter
	ReceiverAwss3SqsMessagesDropped metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ReceiverAwss3ObjectsDropped, err = builder.meter.Int64Counter(
		"otelcol_receiver_awss3_objects_dropped",
		metric.WithDescription("Number of S3 objects dropped because their content cannot be decompressed or decoded. [Development]"),
		metric.WithUnit("{objects}"),
	)
	errs = errors.Join(errs, err)
	builder.ReceiverAwss3SqsMessagesDropped, err = builder.meter.Int64Counter(
		"otelcol_receiver_awss3_sqs_messages_dropped",
		metric.WithDescription("Number of SQS messages deleted because they are not a readable S3 event notification. [Development]"),
		metric.WithUnit("{messages}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
