// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstometricsprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstometricsprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                    metric.Meter
	mu                                       sync.Mutex
	registrations                            []metric.Registration
	ProcessorLogstometricsErrors             metric.Int64Counter
	ProcessorLogstometricsLogsDropped        metric.Int64Counter
	ProcessorLogstometricsLogsProcessed      metric.Int64Counter
	ProcessorLogstometricsMetricsExtracted   metric.Int64Counter
	ProcessorLogstometricsProcessingDuration metric.Int64Histogram
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorLogstometricsErrors, err = builder.meter.Int64Counter(
		"otelcol_processor_logstometrics_errors",
		metric.WithDescription("Number of errors encountered during processing [Development]"),
		metric.WithUnit("{errors}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogstometricsLogsDropped, err = builder.meter.Int64Counter(
		"otelcol_processor_logstometrics_logs_dropped",
		metric.WithDescription("Number of logs dropped when drop_logs is true [Development]"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogstometricsLogsProcessed, err = builder.meter.Int64Counter(
		"otelcol_processor_logstometrics_logs_processed",
		metric.WithDescription("Number of log records processed by the processor [Development]"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogstometricsMetricsExtracted, err = builder.meter.Int64Counter(
		"otelcol_processor_logstometrics_metrics_extracted",
		metric.WithDescription("Number of metrics extracted from logs [Development]"),
		metric.WithUnit("{metrics}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorLogstometricsProcessingDuration, err = builder.meter.Int64Histogram(
		"otelcol_processor_logstometrics_processing_duration",
		metric.WithDescription("Time spent processing logs and extracting metrics [Development]"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
