// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter/internal/metadata"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.LoadbalancerBackendCount.Record(context.Background(), 1)
	tb.LoadbalancerBackendFailOpenTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendLatency.Record(context.Background(), 1)
	tb.LoadbalancerBackendOutcome.Add(context.Background(), 1)
	tb.LoadbalancerBackendQuarantineTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendRequestBytes.Record(context.Background(), 1)
	tb.LoadbalancerBackendRequestBytesTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendRequestItems.Record(context.Background(), 1)
	tb.LoadbalancerBackendRequestItemsTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendRequestTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendRerouteTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendStaleTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendState.Record(context.Background(), 1)
	tb.LoadbalancerBackendSubsetDisplacementTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendTimeoutTotal.Add(context.Background(), 1)
	tb.LoadbalancerBackendUnquarantineTotal.Add(context.Background(), 1)
	tb.LoadbalancerNumBackendUpdates.Add(context.Background(), 1)
	tb.LoadbalancerNumBackends.Record(context.Background(), 1)
	tb.LoadbalancerNumResolutions.Add(context.Background(), 1)
	tb.LoadbalancerNumSelectedBackends.Record(context.Background(), 1)
	AssertEqualLoadbalancerBackendCount(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendFailOpenTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendLatency(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendOutcome(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendQuarantineTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendRequestBytes(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendRequestBytesTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendRequestItems(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendRequestItemsTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendRequestTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendRerouteTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendStaleTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendState(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSubsetDisplacementTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendTimeoutTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendUnquarantineTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumBackendUpdates(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumBackends(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumResolutions(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumSelectedBackends(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
