// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/parquetlogencodingextension/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.ParquetLogEncodingBufferEstimatedBytes.Record(context.Background(), 1)
	tb.ParquetLogEncodingBufferOldestRecordAge.Record(context.Background(), 1)
	tb.ParquetLogEncodingBufferRecords.Record(context.Background(), 1)
	tb.ParquetLogEncodingDroppedRecordsTotal.Add(context.Background(), 1)
	tb.ParquetLogEncodingFlushAttemptTotal.Add(context.Background(), 1)
	tb.ParquetLogEncodingFlushEmptyTotal.Add(context.Background(), 1)
	tb.ParquetLogEncodingFlushFailedTotal.Add(context.Background(), 1)
	tb.ParquetLogEncodingFlushTotal.Add(context.Background(), 1)
	tb.ParquetLogEncodingFlushedBytes.Add(context.Background(), 1)
	tb.ParquetLogEncodingFlushedRecords.Add(context.Background(), 1)
	tb.ParquetLogEncodingTimeToFlush.Record(context.Background(), 1)
	AssertEqualParquetLogEncodingBufferEstimatedBytes(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingBufferOldestRecordAge(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingBufferRecords(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingDroppedRecordsTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingFlushAttemptTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingFlushEmptyTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingFlushFailedTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingFlushTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingFlushedBytes(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingFlushedRecords(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualParquetLogEncodingTimeToFlush(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
