// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/extension/parquetlogencodingextension")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/extension/parquetlogencodingextension")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                   metric.Meter
	mu                                      sync.Mutex
	registrations                           []metric.Registration
	ParquetLogEncodingBufferEstimatedBytes  metric.Int64Gauge
	ParquetLogEncodingBufferOldestRecordAge metric.Int64Gauge
	ParquetLogEncodingBufferRecords         metric.Int64Gauge
	ParquetLogEncodingDroppedRecordsTotal   metric.Int64Counter
	ParquetLogEncodingFlushAttemptTotal     metric.Int64Counter
	ParquetLogEncodingFlushEmptyTotal       metric.Int64Counter
	ParquetLogEncodingFlushFailedTotal      metric.Int64Counter
	ParquetLogEncodingFlushTotal            metric.Int64Counter
	ParquetLogEncodingFlushedBytes          metric.Int64Counter
	ParquetLogEncodingFlushedRecords        metric.Int64Counter
	ParquetLogEncodingTimeToFlush           metric.Int64Histogram
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ParquetLogEncodingBufferEstimatedBytes, err = builder.meter.Int64Gauge(
		"otelcol_parquet_log_encoding_buffer_estimated_bytes",
		metric.WithDescription("Estimated compressed bytes currently buffered in the parquet log encoder [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingBufferOldestRecordAge, err = builder.meter.Int64Gauge(
		"otelcol_parquet_log_encoding_buffer_oldest_record_age",
		metric.WithDescription("Age in seconds of the oldest buffered record in the parquet log encoder [Alpha]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingBufferRecords, err = builder.meter.Int64Gauge(
		"otelcol_parquet_log_encoding_buffer_records",
		metric.WithDescription("Number of log records currently buffered in the parquet log encoder [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingDroppedRecordsTotal, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_dropped_records_total",
		metric.WithDescription("Number of records dropped by the parquet log encoder [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingFlushAttemptTotal, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_flush_attempt_total",
		metric.WithDescription("Number of flush attempts made by the parquet log encoder [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingFlushEmptyTotal, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_flush_empty_total",
		metric.WithDescription("Number of flush attempts that found no buffered parquet records [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingFlushFailedTotal, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_flush_failed_total",
		metric.WithDescription("Number of parquet flush attempts that failed after records were buffered [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingFlushTotal, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_flush_total",
		metric.WithDescription("Number of non-empty parquet buffer flushes [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingFlushedBytes, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_flushed_bytes",
		metric.WithDescription("Bytes emitted by non-empty parquet flushes before S3-level compression [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingFlushedRecords, err = builder.meter.Int64Counter(
		"otelcol_parquet_log_encoding_flushed_records",
		metric.WithDescription("Number of buffered records emitted by non-empty parquet flushes [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ParquetLogEncodingTimeToFlush, err = builder.meter.Int64Histogram(
		"otelcol_parquet_log_encoding_time_to_flush",
		metric.WithDescription("Time in milliseconds from first buffered parquet record to successful non-empty flush [Alpha]"),
		metric.WithUnit("ms"),
		metric.WithExplicitBucketBoundaries([]float64{1, 10, 50, 100, 250, 500, 1000, 5000, 10000, 30000, 60000, 300000, 900000}...),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
